/**
 * Tiny (16x16) encoded samples used to probe a browser's native image decoders.
 * Each blob is produced by the matching codec at 16x16, so a negative probe is
 * a format the platform genuinely cannot decode rather than a missing fixture.
 * They are decoded `as ImageBitmap` by `canDecodeNatively` in `registry.ts`
 * and never shown to the user.
 *
 * Generated with the project's own encoders (@jsquash/png|webp|avif, elheif
 * for HEIC, and the browser's native JPEG encoder). Regenerate if the codecs
 * change; keep them 16x16 so decoding one is effectively free.
 */
const BASE64: Record<string, string> = {
  'image/jpeg':
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdC' +
    'IFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAA' +
    'AADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlk' +
    'ZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAA' +
    'ABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAA' +
    'AAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAA' +
    'AABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEA' +
    'AAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAA' +
    'ACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAA0JCgsKCA0LCgsODg0P' +
    'EyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4O' +
    'DhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09P' +
    'T09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAYEAACAwAA' +
    'AAAAAAAAAAAAAAAABAUiMf/EABUBAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhEAAgIDAAAAAAAAAAAA' +
    'AAAAAAUDBCExYf/aAAwDAQACEQMRAD8AlVI3KjKsblRhWNyoyrG5Umz3+jUstZP/2Q==',
  'image/png':
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACn0lEQVR4Ae3gAZAkSZIkSRKLqpm7' +
    'R0REZmZmVlVVVVV3d3d3d/fMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM' +
    'zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMdHd3d3dXV1VVVVVm' +
    'ZkZGRIS7m5kKz0xmV3d1d3dPz8zMzMxMouC1fQI4AZwATgAngBPACeAEcAI4AZwATgAngBPACUCc' +
    'eG2fAE4AJ4ATwAngBHACOAGcAE4AJ4ATwAngBHACEA99bZ8ATgAngBPACeAEcAI4AZwATgAngBPA' +
    'CeAEcAIQL/faPgGcAE4AJ4ATwAngBHACOAGcAE4AJ4ATwAngBCBe/7V9AjgBnABOACeAE8AJ4ARw' +
    'AjgBnABOACeAE8AJQLzDa/sEcAI4AZwATgAngBPACeAEcAI4AZwATgAngBOA+MDX9gngBHACOAGc' +
    'AE4AJ4ATwAngBHACOAGcAE4AJwDxSa/tE8AJ4ARwAjgBnABOACeAE8AJ4ARwAjgBnABOAOKLX9sn' +
    'gBPACeAEcAI4AZwATgAngBPACeAEcAI4AZwAxLe8tk8AJ4ATwAngBHACOAGcAE4AJ4ATwAngBHAC' +
    'OAGIH31tnwBOACeAE8AJ4ARwAjgBnABOACeAE8AJ4ARwAhC/9to+AZwATgAngBPACeAEcAI4AZwA' +
    'TgAngBPACeAEIP78tX0COAGcAE4AJ4ATwAngBHACOAGcAE4AJ4ATwAlAPPW1fQI4AZwATgAngBPA' +
    'CeAEcAI4AZwATgAngBPACUBceG2fAE4AJ4ATwAngBHACOAGcAE4AJ4ATwAngBHACEH5tnwBOACeA' +
    'E8AJ4ARwAjgBnABOACeAE8AJ4ARwAvhHphor6dSAay4AAAAASUVORK5CYII=',
  'image/webp':
    'UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQABAAAoBCJbACdLoAAwkvDDCqAAD++pMy/HYnBiyK' +
    '721Y97Ui13c0h+a+Bv2kL9ysV/yu6lTq5AAA',
  'image/avif':
    'AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAADybWV0YQAAAAAAAAAoaGRscgAAAAAA' +
    'AAAAcGljdAAAAAAAAAAAAAAAAGxpYmF2aWYAAAAADnBpdG0AAAAAAAEAAAAeaWxvYwAAAABEAAAB' +
    'AAEAAAABAAABGgAAAC4AAAAoaWluZgAAAAAAAQAAABppbmZlAgAAAAABAABhdjAxQ29sb3IAAAAA' +
    'amlwcnAAAABLaXBjbwAAABRpc3BlAAAAAAAAABAAAAAQAAAAEHBpeGkAAAAAAwgICAAAAAxhdjFD' +
    'gQAMAAAAABNjb2xybmNseAACAAIABoAAAAAXaXBtYQAAAAAAAAABAAEEAQKDBAAAADZtZGF0EgAK' +
    'CRgM/9ggQEDQgDIfGAAKKKKEADldZbSgnSf/bCfhD7XzvJ6JQZT0unEh4Q==',
  'image/heic':
    'AAAAHGZ0eXBoZWljAAAAAG1pZjFoZWljbWlhZgAAAw9tZXRhAAAAAAAAACFoZGxyAAAAAAAAAABw' +
    'aWN0AAAAAAAAAAAAAAAAAAAAAA5waXRtAAAAAAABAAAAVGlsb2MAAAAAREAAAgABAAAAAAMzAAMA' +
    'AAAAAAAAtAAAALQAAAAjAAAA1wAAABYAAgAAAAAEIAADAAAAAAAAALQAAAC0AAAADQAAAMEAAAAO' +
    'AAAAOGlpbmYAAAAAAAIAAAAVaW5mZQIAAAAAAQAAaHZjMQAAAAAVaW5mZQIAAAAAAgAAaHZjMQAA' +
    'AAIuaXBycAAAAglpcGNvAAAA2Gh2Y0MBAWAAAAAAAAAAAAC68AD8/fj4AAALBiAAAQAaQAEMAv//' +
    'AWAAAAMAgAAAAwAAAwC6AAAsCQAhAAEALEIBAgFgAAADAIAAAAMAAAMAugAAoIhFy5JMqm4CGgwI' +
    'AAADAAgAAAMAyEAAIgABAAhEAcFxgpkgACAAAQAaQAEMAv//AWAAAAMAgAAAAwAAAwC6AAAsCQAh' +
    'AAEALEIBAgFgAAADAIAAAAMAAAMAugAAoIhFy5JMqm4CGgwIAAADAAgAAAMAyEAAIgABAAdEAcFx' +
    'gpkgAAAAFGlzcGUAAAAAAAAAEAAAABAAAAAQcGl4aQAAAAADCAgIAAAA0Gh2Y0MBAWAAAAAAAAAA' +
    'AAC68AD8/Pj4AAALBiAAAQAaQAEMAv//AWAAAAMAgAAAAwAAAwC6AAAsCQAhAAEAKEIBAgFgAAAD' +
    'AIAAAAMAAAMAugAAwiEXLkkyqbAgAAADACAAAAMDIQAiAAEACEQBwXGCmSAAIAABABpAAQwC//8B' +
    'YAAAAwCAAAADAAADALoAACwJACEAAQAoQgECAWAAAAMAgAAAAwAAAwC6AADCIRcuSTKpsCAAAAMA' +
    'IAAAAwMhACIAAQAHRAHBcYKZIAAAAA5waXhpAAAAAAEIAAAAJ2F1eEMAAAAAdXJuOm1wZWc6aGV2' +
    'YzoyMDE1OmF1eGlkOjEAAAAAHWlwbWEAAAAAAAAAAgABA4ECAwACBIQCBYYAAAAaaXJlZgAAAAAA' +
    'AAAOYXV4bAACAAEAAQAAAcRtZGF0AAAAsE4BBasy/kZsmEFCaa41apFUnvPxS3ZhemFhciBIRVZD' +
    'IEVuY29kZXIgdi4gMi4zLjEtZWEwOWFmNSAtIENvcHlsZWZ0IDIwMTItMjAxNSAtIGh0dHA6Ly91' +
    'bHRyYXZpZGVvLmNzLnR1dC5maS8gLSBvcHRpb25zOiAxNngxNiBkZWJsb2NrPTE6MDowIHNhbz0z' +
    'IGludHJhX3BlcmlvZD02NCBxcD0yNiByZWY9MQCAAAAAHyYBr3j3MJtD0g9BjrRFZ2y5Qjspn1Sk' +
    '15K0namcd8AAAAASUAGEDQIAAHgKAAAYNAAAIW6AAAAAsE4BBasy/kZsmEFCaa41apFUnvPxS3Zh' +
    'emFhciBIRVZDIEVuY29kZXIgdi4gMi4zLjEtZWEwOWFmNSAtIENvcHlsZWZ0IDIwMTItMjAxNSAt' +
    'IGh0dHA6Ly91bHRyYXZpZGVvLmNzLnR1dC5maS8gLSBvcHRpb25zOiAxNngxNiBkZWJsb2NrPTE6' +
    'MDowIHNhbz0zIGludHJhX3BlcmlvZD02NCBxcD0yNiByZWY9MQCAAAAACSYBrvDxlv4uPgAAAApQ' +
    'AYQFAgAA94CA',
}

/**
 * Decodes a probe sample to bytes on first use. `atob` returns a binary
 * string; the loop copies it into a Uint8Array without a UTF-8 round trip.
 */
export function decodeSample(mimeType: string): Uint8Array<ArrayBuffer> | null {
  const base64 = BASE64[mimeType]
  if (!base64) return null
  const binary = atob(base64)
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index)
  }
  return bytes
}
